// generated by the following code:
//
// require('gradient-string')([
//   { color: '#8adae6', pos: 0 },
//   { color: '#0c8da0', pos: 0.1 },
//   { color: '#14acc2', pos: 1 }
// ])('Sails.js - The MVC framework for Node.js')

// Use the output directly here to keep the bundle small.

const banner =
'\x1B[38;2;138;218;230mS\x1B[39m\x1B[38;2;96;192;207ma\x1B[39m\x1B[38;2;54;167;183mi\x1B[39m\x1B[38;2;12;141;160ml\x1B[39m\x1B[38;2;12;142;161ms\x1B[39m\x1B[38;2;13;143;162m.\x1B[39m\x1B[38;2;13;144;163mj\x1B[39m\x1B[38;2;13;145;165ms\x1B[39m \x1B[38;2;13;146;166m-\x1B[39m \x1B[38;2;14;147;167mT\x1B[39m\x1B[38;2;14;148;168mh\x1B[39m\x1B[38;2;14;149;169me\x1B[39m \x1B[38;2;14;150;170mM\x1B[39m\x1B[38;2;15;151;171mV\x1B[39m\x1B[38;2;15;152;172mC\x1B[39m \x1B[38;2;15;153;174mf\x1B[39m\x1B[38;2;15;154;175mr\x1B[39m\x1B[38;2;16;155;176ma\x1B[39m\x1B[38;2;16;157;177mm\x1B[39m\x1B[38;2;16;158;178me\x1B[39m\x1B[38;2;17;159;179mw\x1B[39m\x1B[38;2;17;160;180mo\x1B[39m\x1B[38;2;17;161;182mr\x1B[39m\x1B[38;2;17;162;183mk\x1B[39m \x1B[38;2;18;163;184mf\x1B[39m\x1B[38;2;18;164;185mo\x1B[39m\x1B[38;2;18;165;186mr\x1B[39m \x1B[38;2;18;166;187mN\x1B[39m\x1B[38;2;19;167;188mo\x1B[39m\x1B[38;2;19;168;189md\x1B[39m\x1B[38;2;19;169;191me\x1B[39m\x1B[38;2;19;170;192m.\x1B[39m\x1B[38;2;20;171;193mj\x1B[39m\x1B[38;2;20;172;194ms\x1B[39m'

module.exports = banner
